name: bomb_game
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+25

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  google_fonts: ^6.2.1
  package_info_plus: ^8.0.0
  confetti: ^0.7.0
  google_mobile_ads: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_hooks: ^0.20.5
  app_tracking_transparency: ^2.0.6
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter_icons:
  ios: true
  image_path: "assets/images/bomb_game_icon.png"
  remove_alpha_ios: true



flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/sounds/
    - assets/audio/bgm.mp3
    - assets/animations/

 
